### ISSUE TITLE
[Feature request] Respect hyphenated word in tokenizer

### ISSUE THREAD

**Issue by SPiCaRiA** [scambier/obsidian-omnisearch#225]
Hi, thank you for making this great plug-in!

I am used to using hyphenated words (if that's the correct form) in my notes, e.g., plug-in instead of plugin. However, this gets troublesome when using Omnisearch. It seems that plug-in will be split into two terms *plug* and *in* by the current tokenizer. In practice, hyphens are primarily used to connect words into one. Therefore they should not be treated as separate terms in the vocabulary.

As the Minisearch library supports fuzzy search, I believe we can still match *plugin* and *plug-in* interchangeably, but not *plugin* and *plug* - *in* (two terms).

Let me know what you think!

**Comment by jwhitley** [comment]
I'll second this request. I had also expected to be able to use the double-quote `"exact expression"` syntax to protect hyphens, but that doesn't work. E.g. I have a company name of the form A-Company in my notes... and the tokenizer breaks out the single letter `a` as a token making the search effort completely useless.

I also find it a bit unusual that MiniSearch even accepts single-letter tokens in the absence of token order/proximity as an influence on results rank. e.g. smarter engines would see a query `A-Company` and process it into a search set like `["a-company", "acompany", "a company"]`, and perhaps "company" on its own at lower rank. But they would drop the singleton `a` token as too short to be relevant.

**Comment by scambier** [comment]
(don't mind the butchered PR)

This is fixed and published in the latest beta release.

**Comment by ManiMixer** [comment]
I've tested 1.15.0-beta.1 and this doesn't fix the issue - I presume that the other changes in the release prevent the regex change from working.

To be specific neither `YYYY-MM-DD` or `"YYYY-MM-DD"` work as expected. I will get results with YYYY-mm-dd where mm and dd are not the desired MM/DD as the first results, with the actual one I want buried further down the result list.

**Comment by scambier** [comment]
There's no guarantee for what will be the first result. When you search for `yyyy-mm-dd`, the search engine will simply look for the tokens `yyyy`, `mm`, & `dd`, and will weight the results accordingly. So if you have a note where `yyyy` appears 20 times, and a single note with the exact `yyyy-mm-dd`, chances are the note with the 20 `yyyy` will appear on top.

See this example:
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/3893d801-c367-4041-9d20-5a5c1385a79f)

But yeah, the quotes search is broken, I'll take a look at it.
